const PDFDocument = require('pdfkit');
const fs = require('fs').promises;
const fsSync = require('fs'); // Needed for checking logo existence
const path = require('path');

class InvoiceGenerator {
    constructor() {
        this.fonts = {
            regular: 'Helvetica',
            bold: 'Helvetica-Bold',
        };
        this.colors = {
            primary: '#0056b3',    // Blue
            dark: '#333333',       // Dark Gray
            light: '#666666',      // Light Gray
            bgLight: '#f9f9f9',    // Light Backgrounds
            danger: '#d9534f'      // Red
        };
        this.currency = 'Rs.'; // Changed from symbol to text to fix "superscript" font issues

        this.autoGeneratedPath = path.join(process.cwd(), 'uploads', 'invoices', 'auto-generated');
        // Assumption: Logo is stored here. Change this path if your logo is elsewhere.
        this.logoPath = path.join(process.cwd(), 'public', 'logo.png');
        this.initialized = false;
    }

    async init() {
        if (this.initialized) return;
        try {
            await fs.mkdir(this.autoGeneratedPath, { recursive: true });
            this.initialized = true;
        } catch (error) {
            console.error('❌ Failed to init invoice generator:', error);
        }
    }

    async generateAutoInvoice(order, user) {
        if (!this.initialized) await this.init();

        const pdfBuffer = await this._createInvoicePDF(order, user);
        const fileName = `INV-${order.orderNumber}-${Date.now()}.pdf`;
        const filePath = path.join(this.autoGeneratedPath, fileName);
        const pdfUrl = `/uploads/invoices/auto-generated/${fileName}`;

        await fs.writeFile(filePath, pdfBuffer);
        return { pdfBuffer, filePath, fileName, pdfUrl, invoiceNumber: `INV-${order.orderNumber}` };
    }

    async _createInvoicePDF(order, user) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50, size: 'A4' });
                const chunks = [];

                doc.on('data', chunk => chunks.push(chunk));
                doc.on('end', () => resolve(Buffer.concat(chunks)));
                doc.on('error', err => reject(err));

                this._generateHeader(doc, order);
                this._generateCustomerInfo(doc, order, user);
                const tableBottomY = this._generateInvoiceTable(doc, order);
                this._generateSummarySection(doc, order, tableBottomY);
                this._generateFooter(doc);

                doc.end();
            } catch (error) {
                reject(error);
            }
        });
    }

    _generateHeader(doc, order) {
        const topY = 50;
        let leftX = 50;
        let textTopY = topY;

        // 1. LOGO LOGIC
        // Check if logo exists synchronously to avoid async issues in PDF generation
        if (fsSync.existsSync(this.logoPath)) {
            doc.image(this.logoPath, 50, topY, { width: 150 }); // Larger logo
            textTopY = topY + 50; // Text goes below the logo
        } else {
            // 2. COMPANY INFO (Text Fallback if no logo)
            doc.font(this.fonts.bold).fontSize(20).fillColor(this.colors.primary)
                .text('iTech Computers', leftX, topY);
            textTopY = topY + 25;
        }

        doc.font(this.fonts.regular).fontSize(9).fillColor(this.colors.light) // Slightly smaller font for address
            .text('Professional Computer Solutions', leftX, textTopY)
            .moveDown(0.3)
            .text('iTech Computers, RBT Mall, Meyyanur Bypass Rd,', leftX)
            .text('opp. to iplanet, Meyyanur, Salem, Tamil Nadu 636004', leftX)
            .moveDown(0.3)
            .text('Email: itechcomputersno7@gmail.com', leftX)
            .text('Phone: +91 98765 43210', leftX);

        // 3. INVOICE META (Right Side - Fixed Alignment)
        // We set a specific width and rely on 'align: right' relative to that box
        const rightX = 345;
        const rightWidth = 200;

        doc.font(this.fonts.bold).fontSize(24).fillColor(this.colors.dark)
            .text('INVOICE', rightX, topY, { width: rightWidth, align: 'right' });

        doc.font(this.fonts.regular).fontSize(10).fillColor(this.colors.light);
        doc.text(`Invoice #: INV-${order.orderNumber}`, rightX, topY + 35, { width: rightWidth, align: 'right' });
        doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, rightX, topY + 50, { width: rightWidth, align: 'right' });

        // Header Divider
        doc.moveTo(50, 160).lineTo(545, 160).lineWidth(3).strokeColor(this.colors.primary).stroke();
    }

    _generateCustomerInfo(doc, order, user) {
        const y = 180;
        const shipping = order.shippingAddress || {};

        // Grey Bar
        doc.rect(50, y, 4, 90).fillColor('#dddddd').fill();

        // Title
        doc.font(this.fonts.bold).fontSize(12).fillColor(this.colors.primary)
            .text('BILL TO', 65, y);

        // Address Details
        doc.font(this.fonts.regular).fontSize(10).fillColor(this.colors.dark);

        let currentY = y + 20;
        const lineHeight = 14;

        // Name
        const name = `${shipping.firstName || user.firstName || ''} ${shipping.lastName || user.lastName || ''}`;
        doc.text(`Name: ${name}`, 65, currentY);
        currentY += lineHeight;

        // Address Line 1
        if (shipping.addressLine1) {
            doc.text(shipping.addressLine1, 65, currentY);
            currentY += lineHeight;
        }

        // City, State, Zip
        const cityState = `${shipping.city || ''}, ${shipping.state || ''} - ${shipping.pincode || ''}`;
        doc.text(cityState, 65, currentY);
        currentY += lineHeight;

        // Contact
        const phone = shipping.phone || shipping.mobile || user.phone || 'N/A';
        const email = shipping.email || user.email || 'N/A';
        doc.text(`Mobile: ${phone}`, 65, currentY);
        currentY += lineHeight;
        doc.text(`Email: ${email}`, 65, currentY);
    }

    _generateInvoiceTable(doc, order) {
        let y = 310; // Moved up to reduce padding
        const startX = 50;

        // Header
        doc.rect(startX, y, 495, 20).fillColor('#f4f4f4').fill();
        doc.font(this.fonts.bold).fontSize(8).fillColor(this.colors.dark);

        const col = { desc: 55, qty: 290, price: 330, gst: 385, taxAmt: 425, total: 480 };

        doc.text('DESCRIPTION', col.desc, y + 6);
        doc.text('QTY', col.qty, y + 6, { width: 30, align: 'center' });
        doc.text('UNIT PRICE', col.price, y + 6, { width: 50, align: 'right' });
        doc.text('GST %', col.gst, y + 6, { width: 30, align: 'center' });
        doc.text('TAX AMT', col.taxAmt, y + 6, { width: 50, align: 'right' });
        doc.text('TOTAL', col.total, y + 6, { width: 60, align: 'right' });

        y += 25;
        doc.font(this.fonts.regular).fontSize(8).fillColor(this.colors.dark);

        const items = order.items || [];
        items.forEach((item) => {
            // Price Calculation
            let rawPrice = Number(item.discountedPrice) || Number(item.price) || (Number(item.total) / Number(item.quantity)) || 0;
            const qty = Number(item.quantity) || 1;

            // GST FIX: Check if taxRate is 0.18 (decimal) or 18 (integer)
            let gstRate = 18; // Default
            if (item.taxRate) {
                // If taxRate is less than 1 (e.g., 0.18), convert to percentage (18)
                // If taxRate is greater than 1 (e.g., 18), keep as is
                gstRate = item.taxRate < 1 ? item.taxRate * 100 : item.taxRate;
            }

            // Calculation and rounding to remove decimals per user request
            const price = Math.round(rawPrice);
            const unitTaxAmt = Math.round(price * (gstRate / 100));
            const inclusiveUnitPrice = price + unitTaxAmt;
            const lineTotal = inclusiveUnitPrice * qty;

            // Name
            let itemName = item.name || 'Product Item';
            if (item.variant && item.variant.name && !itemName.includes(item.variant.name)) {
                itemName += ` - ${item.variant.name}`;
            }

            // Draw Row
            doc.text(itemName, col.desc, y, { width: 230, lineGap: 2 });
            doc.text(qty.toString(), col.qty, y, { width: 30, align: 'center' });
            doc.text(`${price.toLocaleString('en-IN')}`, col.price, y, { width: 50, align: 'right' });
            doc.text(`${gstRate}%`, col.gst, y, { width: 30, align: 'center' });
            doc.text(`${unitTaxAmt.toLocaleString('en-IN')}`, col.taxAmt, y, { width: 50, align: 'right' });
            doc.text(`${lineTotal.toLocaleString('en-IN')}`, col.total, y, { width: 60, align: 'right' });

            // Bottom border
            let rowHeight = doc.heightOfString(itemName, { width: 230 }) || 10;
            let currentBottomY = y + rowHeight + 5;
            doc.moveTo(startX, currentBottomY).lineTo(545, currentBottomY).lineWidth(0.5).strokeColor('#eeeeee').stroke();

            y = currentBottomY + 10;
        });

        return y;
    }

    _generateSummarySection(doc, order, startY) {
        let y = startY + 15; // Reduced padding
        // If Y is too low, add page? (Optional check)
        if (y > 700) { doc.addPage(); y = 50; }

        const summaryX = 350;

        doc.rect(summaryX, y, 195, 105).fillColor('#f9f9f9').fill();

        let sumY = y + 12;
        const labelX = summaryX + 10;
        const valX = summaryX + 110;

        const printRow = (label, value, isBold = false) => {
            doc.font(isBold ? this.fonts.bold : this.fonts.regular).fontSize(10).fillColor('#333')
                .text(label, labelX, sumY);
            doc.text(value, valX, sumY, { width: 70, align: 'right' });
            sumY += 18;
        };

        const pricing = order.pricing || {};
        const subtotal = Math.round(pricing.subtotal || pricing.totalPrice || 0);
        const tax = Math.round(pricing.tax || pricing.totalGst || 0);
        const shipping = Math.round(pricing.shipping || pricing.deliveryCharge || 0);
        const total = Math.round(pricing.total || pricing.finalAmount || 0);

        printRow('Subtotal', `${this.currency} ${subtotal.toLocaleString('en-IN')}`);
        printRow('Shipping', `${this.currency} ${shipping.toLocaleString('en-IN')}`);
        printRow('Total GST', `${this.currency} ${tax.toLocaleString('en-IN')}`);

        doc.moveTo(summaryX, sumY).lineTo(545, sumY).strokeColor('#333').stroke();
        sumY += 10;

        doc.font(this.fonts.bold).fontSize(12).fillColor(this.colors.primary)
            .text('Total Due', labelX, sumY);
        doc.text(`${this.currency} ${total.toLocaleString('en-IN')}`, valX, sumY, { width: 70, align: 'right' });
    }

    _generateFooter(doc) {
        const bottomY = 750;
        doc.font(this.fonts.regular).fontSize(8).fillColor('#888')
            .text('Thank you for your business!', 50, bottomY, { align: 'center', width: 500 })
            .text('This is a computer-generated invoice. No signature required.', 50, bottomY + 12, { align: 'center', width: 500 });
    }
}

module.exports = new InvoiceGenerator();